default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""


development:
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"


production:
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false


heroku:
  ALLOWED_HOSTS:
    - .obliviscor.herokuapp.com
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false


test:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"


travis:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
