default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: false
  EMAIL_USE_TLS: false
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0


development:
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SIDE_ID: 1


production:
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false


heroku:
  ALLOWED_HOSTS:
    - .obliviscor.herokuapp.com
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false


test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SIDE_ID: 1


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SIDE_ID: 1
