default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  TIME_ZONE: ""


development:
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


production:
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0


heroku:
  ALLOWED_HOSTS:
    - .obliviscor.herokuapp.com
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0


test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
