# Generated by Django 3.0.5 on 2020-04-20 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import applications.reminders.models
import applications.reminders.utils.consts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=applications.reminders.models._now),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notify_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("DONE", "Done"),
                            ("ENQUEUED", "Enqueued"),
                            ("NOTIFIED", "Notified"),
                        ],
                        default=applications.reminders.utils.consts.ReminderStatus[
                            "CREATED"
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="participated_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
