# Generated by Django 3.0.5 on 2020-04-26 13:24

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reminders", "0003_auto_20200422_0431"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="notify_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="participated_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("DONE", "Done"),
                    ("ENQUEUED", "Enqueued"),
                    ("NOTIFIED", "Notified"),
                ],
                db_index=True,
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
