# Generated by Django 3.0.5 on 2020-04-26 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0004_auto_20200426_1624"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder", options={"ordering": ["-notify_at", "-created_at"]},
        ),
    ]
